cburstedde/p4est

src/p4est.c
Really nothing of substance, but I noticed it while reading your code :-)
=> Fix a typo.

INSTALL_WINDOWS
Instructions for Windows build using MSYS2/MinGW64 toolchain.
=> Instruction for Windows build and linking with MS Visual Studio

doc/author_kestener.txt, example/simple/simple2.c, src/p4est_connectivity.c, src/p4est_connectivity.h, src/p4est_geometry.c, src/p4est_geometry.h
add 2d connectivity and geometry:
- icosahedron
- shell2d (adapted from shell in 3d)
=> add icosahedron and shell2d connectivity/geometry

src/p4est_vtk.c
Following up on issue with CI for CMake #31
Add preprocessor macro.
=> Fix CMake build

.github/workflows/ci.yml, .github/workflows/ci_cmake.yml, CMakeLists.txt, CMakePresets.json, cmake/compilers.cmake, cmake/options.cmake, cmake/sc.cmake, example/CMakeLists.txt, test/CMakeLists.txt
* Fix p4est examples library finding/linking
* remove unused CMake presets
=> CMake presets cleanup and link improvements

.github/workflows/ci_cmake.yml
Updates path to MSYS2 as its GitHub Actions changed its path since previous PR was made
=> CI:windows: update MSYS2 path

src/p8est_connectivity.c
Following up on issue # 133.
Make the code conform to C89 and older compilers.
=> Fix c89 construct

.github/workflows/ci_cmake.yml
Upload artifacts for cmake build
=> upload log files as artifacts

.github/workflows/ci.yml, .github/workflows/ci_darwin.yml
Added new ci_darwin.yml file to test p4est builds on MacOS.
=> Feature darwin ci

example/steps/p4est_step3.c
Currently we update a derivative and compare to the same variable which leads to always-true condition.
Check if the derivative variable was updated and proceed to the corresponding branch of if-else statement.
=> Estimation of a derivative in p4est_step3 example

src/p4est_bits.c, src/p4est_bits.h, src/p4est_to_p8est.h, src/p8est_bits.h
Proposal for a function to check if two related quadrants share a face.
=> Feature tree boundary

doc/author_fikl.txt
Added my license agreement. 
Glad to see `p4est` is still going strong!
=> Add license change statement

example/simple/simple2.c, example/simple/simple3.c
Very minor changes, just slightly update simple examples to demo the "brick" connectivity (illustrate tree numbering).
=> Add brick connectivity to simple example

cmake/options.cmake, cmake/sc.cmake
=> cmake variable sc_external is now a cmake option.

cmake/jansson.cmake
This is a follow-up; this issue was not entirely fixed in https://github.com/cburstedde/p4est/pull/229
Following up on issue #227
=> Fix linking to lib jansson (when available).

doc/author_hongli.txt, example/simple/simple3.c, src/p4est_connectivity.c, src/p8est_connectivity.c, src/p8est_connectivity.h
New 3D example in p8est_simple
- a 3d extruded version of 2d drop example
- fix the warnings of p8est_connectivity during doxygen
=> Hongli simple: New 3D example in p8est_simple

doc/author_heister.txt
=> add heister as author

doc/author_carlin.txt
=> Add Carlin as author

AUTHORS, doc/author_lahnert.txt
Similar to previous PR, but with this version mail address is also updated AUTHORS file.
=> Feature fix mail address including update to AUTHORS file

example/gmt/gmt_models.c
Quick fix to a typo in my last PR.
=> Feature GMT sphere: fixed typo causing segfault

doc/author_kirilin.txt
=> Add license

.github/workflows/ci_cmake.yml, src/p4est_connectivity.c, src/p4est_connectivity.h, src/p4est_iterate.h, src/p4est_lnodes.c, src/p4est_lnodes.h, src/p4est_to_p8est.h, src/p8est_connectivity.c, src/p8est_connectivity.h, src/p8est_iterate.h, src/p8est_lnodes.h
- Introduce an explicit typedef for the iterator face sides
- Add lookup tables for the face code of hanging corners
- Add lookup tables for boundary point 
- Remove gcc-13 from the CI
Any comments @tisaac, since these relate to code contributed by you?
=> Feature variable updates

.github/workflows/ci_cmake.yml, .github/workflows/composite-deps/action.yml, .github/workflows/composite-pkg/action.yml, .github/workflows/composite-unix/action.yml, cmake/options.cmake
Like libsc #178, #182, and #184
* no default install prefix as best practice
* simply CI YaML w/o compiler versions like libsc
=> CMake updates like libsc
