- src/p4est.c
- src/p4est_base.h
This should be the correct abs function for `p4est_gloidx_t`.  As I understand it (from section 5.2.4.2.1 of the [C99 Standard](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf)) `long long` will be at least as big as a `int64_t`.
> Define an abs macro for gloidx

- src/p4est_plex.c
The invariant I was using worked for pestc numbering, not for p4est
numbering.  Thanks to Stefano Zampini for pointing both this and the
previous bug out.
> plex: fix child face cone orientations

- src/Makefile.am
- src/p4est_empty.c
- src/p4est_empty.h
- src/p4est_to_p8est_empty.h
- src/p6est_empty.c
- src/p6est_empty.h
- src/p8est_empty.c
- src/p8est_empty.h
The idea of this pull request is to allow a user to add functionality to the p4est library without having to re-bootstrap after pulling a tarball or patching existing p4est files. For instance, a user may want to add accessor functions to p4est structs to linking with a second language.
Right now my workflow for doing this is patch p4est source files prior to build (so that I can just grab the tarball off the web), but this means that I need to create a new patch file every time I want to add a feature which is a bit clumsy.
> Application stub files

- doc/author_ranocha.txt
- src/p4est_base.c
- src/p4est_base.h
- test/Makefile.am
- test/test_version.c
This PR is similar to https://github.com/cburstedde/libsc/pull/24 and https://github.com/cburstedde/libsc/pull/25.
- I implemented functions returning the full version as string and the major/minor/point versions as `int`s.
- I added corresponding tests and verified that they pass locally.
- I added a license statement for my contributions in `docs`.
- I ran `p4estindent` and discarded changes to `__attribute__`.
> add version functions

- doc/author_krasnansky.txt
- src/p4est_to_p8est.h
- src/p4est_vtk.c
- src/p4est_vtk.h
- src/p8est_vtk.h
Following up on issue #94
Exposed already implemented function `p4est_vtk_write_cell_datav` for writing vtk cell data using va_list instead of only variadic arguments.
Added (I hope) clear enough doxygen documentation on usage.
Useful for wrapping possibilities, since variadic arguments cannot be passed any other way than va_list.
> Exposed 'p4est_vtk_write_cell_datav' function for users

- .github/workflows/ci_cmake.yml
- CMakeLists.txt
- CMakePresets.json
- cmake/Config.cmake.in
- cmake/GitSubmodule.cmake
- cmake/install.cmake
- cmake/sc.cmake
- example/CMakeLists.txt
previously I directly added libsc to p4est CMake project. This created undesired mixing of project scopes, such that libsc did not install correctly when built with p4est. This PR eliminates that problem and clarifies linking by keeping libsc scope totally separate from p4est in CMake.
> CMake: correct autobuild of libsc

- src/p4est_vtk.c
- src/p4est_vtk.h
- src/p8est_vtk.h
Following up on issue #105  .
Leak happened every time you did not write out level and/or rank, since deallocation of always allocated variables during normal execution happened inside of `if` statements.
No longer always allocating uint8_data, since only `if (write_level)` statements uses it. Now this array is allocated and deallocated inside of this statement.
Variable `locidx_data` is always deallocated right after the `if (write_rank)` statement. Of course proper deallocations in case something goes wrong are in place.
This PR is a little 'hacky' since it is directly influenced by my previous one and both of them are editing the same piece of code.
> Vtk cell data memory leak

- src/p4est_vtk.c
- src/p4est_vtk.h
- src/p8est_vtk.h
Following up on issue #94.
I've implemented vtk write cell data variant with arrays, since I needed it. I've tested with scalars and random vector array (don't have any valid vectors to test it on atm). 
Implementation is mostly old `p4est_vtk_write_cell_datav` function (one with va_list), with some parts removed (assert on last argument being `p4est_vtk_context_t`, allocation for `values` variable, freeing `values`). It uses `values` straight from argument. `names` variable had to be kept because of the "comma separator" operations.
To prevent code duplication I also reimplemented `p4est_vtk_write_cell_datav` function using the new `p4est_vtk_write_cell_data` one, where I allocate needed arrays and initialize them using va_list values.
So after all these changes the …
> Implement p4est_vtk_write_cell_data function

- doc/author_schlottke-lakemper.txt
- src/p4est_connectivity.c
We have noted that `p4est_connectivity_getline_upper` sometimes fails on Windows (not always - it seems to depend on the actual C library version used). The problem is rooted in the following lines:
https://github.com/cburstedde/p4est/blob/3a78fd2d3a45d27a96db108e042838d0da12591c/src/p4est_connectivity.c#L4598-L4603
After reading the next character from the stream with `fgetc`, it is converted to uppercase using `toupper` and then checked for the `EOF` (end of file) marker. This is OK on Linux (and presumably macOS), since
> If c is a lowercase letter, toupper() returns its uppercase equivalent, if an uppercase representation exists in the current locale.  Otherwise, it returns c.
([ref](https://man7.org/linux/man-pages/man3/toupper.3.html)). Thus, if `c` is actually `EOF` (typically …
> Fix EOF detection in `p4est_connectivity_getline_upper` on Windows

- INSTALL_WINDOWS
- doc/author_schlottke-lakemper.txt
- src/p4est.c
- src/p6est.c
Following up on issue #113.
After opening the existing files in `p4est_save_ext`/`p6est_save_ext` in "append" mode, an additional call to `fseek` ensures that the file position indicator is moved to the end of the file. On Linux/macOS this should be a no-op, since the file position indicator is already at the end of the file. On Windows, however, this fixes the issues with a zero return value from `ftell` as reported in #113.
P.S.: I realize that the contributing guidelines ask for the creation of an issue first. However, since I had a possible fix already available, I just went ahead to show a possible remedy :-)
Closes #113.
> Fix `p4est_save_ext` on Windows

- src/p4est_algorithms.c
- src/p4est_ghost.c
- src/p6est.c
Following up on issue # .
For windows OS 'htonl' resides in winsock.h
> htonl for win32

- src/p6est.h
- src/p6est_lnodes.h
In calls to `replace_fn` the number of out layers should be set to `4` when horizontal coarsening. See docs for `p6est_replace_t` in `src/p6est.h`.
> Update some p6est docs

- src/p4est_bits.c
- src/p4est_bits.h
- src/p4est_connectivity.c
- src/p4est_connectivity.h
- src/p4est_plex.c
- src/p4est_to_p8est.h
- src/p6est.c
- src/p8est_bits.c
- src/p8est_bits.h
- src/p8est_connectivity.c
- src/p8est_connectivity.h
- test/Makefile.am
- test/test_neighbor_transform2.c
- test/test_neighbor_transform3.c
- test/test_plex2.c
There are four parts to this PR
Self-explanatory.
- `p4est_coordinates_compare()`
- `p4est_coordinates_transform_face()`
- `p8est_coordinates_transform_edge()`
From the commit messages:
> It is insufficient just to transform nodes because nodes are restricted to being at valid quadrant corners, so not all coordinates can be represented by nodes.
>
> Likewise, the coordinates can be sorted in Morton order even without a level attached, which is useful for canonicalizing points between trees, so we add this capability.
- typedef `p4est_neighbor_transform_t`
- `p4est_connectivity_get_neighbor_transforms()`
- `p4est_neighbor_transform_coordinates()` and `p4est_neighbor_transform_coordinates_reverse()`
- `p4est_neighbor_transform_quadrant()` and `p4est_neighbor_transform_quadrant_reverse()` …
> Add generic neighbor transformations and use them to fix periodic coordinates for plex

- src/p4est.c
- src/p4est_communication.c
- src/p4est_communication.h
- src/p4est_to_p8est.h
- src/p8est_communication.h
Implement a function to compute the global first quadrant array for a uniform partition. This function is used in the respective places in p4est. This PR is a preparation for the parallel I/O PR since this function is required for the upcoming code.
> Function for uniform global first quadrant array

- src/p4est_extended.h
- src/p4est_io.c
- src/p4est_io.h
- src/p8est_extended.h
- src/p8est_io.h
Proposed changes: There was one macro that did not use `p4est_file_error_cleanup`. This caused errors if one uses OpenMPI instead of MPICH since the related place in the code had a MPICH specifc assumption. This is fixed by using `p4est_file_error_cleanup` in the respective code place.
Beside these changes this PR fixes some typos in the documentation and a compiler warning due to missing type casts.
> Use p4est_file_error_cleanup in all clean up macros

- src/p4est_extended.h
- src/p4est_io.c
- src/p4est_io.h
- src/p8est_extended.h
- src/p8est_io.h
- For function parameters to read strings we use `char abc*` instead of char `abc[NUM]` to avoid compiler warnings classified as string overread in case of strings that are shorter than `NUM - 1`. These warnings appear because GCC 11.2 differentiates between `TYPE* abc` and `TYPE abc[]`
(cf. https://github.com/pmodels/mpich/pull/5749).
- For function parameters to write strings we do the same changes for consistency.
> Fix overread warnings

- src/p4est_io.c
Proposed changes: This PR avoids warnings due to string truncation by the usage of `strncpy`. These warnings are prevented by using the dedicated function `sc_strcopy` (cf. https://github.com/cburstedde/libsc/pull/89) in libsc.
> Fix string truncation warnings

- .github/workflows/ci_cmake.yml
Since Github actions is using Ubuntu 22.04 now and therefore can not install older compiler versions anymore, we fix Ubuntu 20.4 as OS to test older versions of GCC and Clang with Cmake.
> CI: Fix Ubuntu version

- src/p8est_bits.h
One function in p8est_bits.h needed a fix for its name. As per conventions it should be 'p8est_neighbor_transform_quadrant_reverse' instead of 'p4est_neighbor_transform_quadrant_reverse'.
> Minor typo fix for p8est function name.

- src/p4est_base.c
- src/p4est_base.h
This adds the first part of the functionality as discussed in #178, i.e., the ability to check if p4est has already been initialized through a function `p4est_is_initialized`.
I'm not sure if this needs anything else - or if this is even the right target branch for the next release - but I just thought I'd get the discussion started by opening a PR to iterate on.
cc @ranocha
> Add function to check if p4est has been initialized

- cmake/config.cmake
- cmake/options.cmake
- cmake/p4est_config.h.in
- configure.ac
- example/steps/p4est_step3.c
- src/p4est_extended.h
- src/p4est_io.c
- src/p4est_io.h
- src/p4est_to_p8est.h
- src/p8est_extended.h
- src/p8est_io.h
- test/test_io2.c
Proposed changes: Since we are planning to release an updated parallel data file format for p4est, we deprecate the old one to clarify that it will be replaced soon. The old data file format and all corresponding functionality like the simulation restart in `p{4,8}est_step3` can be activated by `--enable-file-deprecated` as configure flag for autotools or via the variable `enable-file-deprecated` in CMake.
The `p{4,8}est_{load,save}` functionality is unaffected and besides the functions for the data file format `p{4,8}est_file_*` including its tests and the restart functionality in `p{4,8}est_step3` nothing is changed and in particular no other existing functionality of p4est breaks.
> Deprecate data file format

- .github/workflows/ci_cmake.yml
Just like https://github.com/cburstedde/libsc/pull/113
For GitHub Actions CI:
* GCC 12 is now also available
* CMake 3.26 is now used, which does not have CMake{Error,Output}.log anymore, replaced by CMakeConfigureLog.yaml
* CTEST_NO_TESTS_ACTION: "error" is in case something is amiss in the CMakeLists.txt that accidentally disabled all tests, this environment variable fails CTest if no tests are enabled.
As I had done previously in libsc CMake CI, to make the CI tests run faster, I only test with GCC 9-12
> CI:CMake: add GCC-12, work with CMake 3.26 runner default

- .github/workflows/ci_cmake.yml
- example/CMakeLists.txt
The examples were not intended to be run in the CI
> cmake:example: don't try to run test in CI

- doc/author_prj-.txt
- src/p4est_base.h
- src/p4est_connectivity.h
```warning: a function declaration without a prototype is deprecated in all versions of C```
> Fix -Wstrict-prototypes

- CMakeLists.txt
- cmake/jansson.cmake
This commit closely follow json support in libsc cmake build system.
This commit is currently harmless, it does almost nothing if libsc version is older than the merge which introduced json support in libsc.
I suggest to merge current MR, right before updating libsc git submodule.
> Add json support in cmake build system

- example/CMakeLists.txt
This was forgotten in MR #205 because examples are built in a separate sub-project.
> Fix example link when jansson is needed by libsc in cmake.

- cmake/config.cmake
Following up on issue #218  .
P4EST_ENABLE_DEBUG shouldn't be defined in RelWithDebInfo cmake build mode. See #218
cmake variable P4EST_ENABLE_DEBUG is now only defined in Debug cmake build mode.
> Symbol P4EST_ENABLE_DEBUG should only be defined in DEBUG mode.

- example/balance_seeds/balance_seeds2.c
Following up on issue #186  .
adapt the coordinates of center quadrant because P8EST_MAXLEVEL is now 30 (not 19 anymore).
> fix balance seed example (3d).

- cmake/jansson.cmake
Following up on issue #227 
- make sure SC_HAVE_JSON is properly defined
> Fix linking with lib jansson

- cmake/sc.cmake
We should not require that git is installed on the build platform; the archive file contains a copy of libsc sources.
One way to test this PR would be to re-create an archive file.
Following up on issue #217 .
> Fix build archive when git executable is not available

- example/simple/simple2.c
- src/p4est_connectivity.c
- src/p4est_connectivity.h
Doxygen: deal with warnings in p4est_connectivity.h during document generation.
> Doxygen: Fix warnings in p4est_connectivity

- src/p4est_search.c
In the relatively new function p4est_search_reorder, we accept a parameter to switch level skipping on or off as an optimization. If on and only a single leaf is contained in a search quadrant, we directly skip down to the leaf as next quadrant to consider.
We fix the bug that the quadrant was not real when skipping was off.
> p4est_search: fix to pass true quadrant

- src/p4est_io.c
Currently, the function `p4est_file_error_code` does not accept MPI error codes that we do not expect according to our wrapped MPI error codes. However, error codes depend on the concrete MPI implementation and in particular newer MPI implementation may cause returning error codes that can not be interpreted in the current way , which currently leads to an abort. 
Proposed changes: Instead of calling `SC_ABORT_NOT_REACHED ()` in the case of an unkown error code we always translate such error codes to `P{4,8}EST_FILE_ERR_UNKOWN`.
> p4est_file: Accept new MPI error codes

- doc/author_markert.txt
- src/p4est_base.c
- src/p4est_base.h
In some scenarios it is useful to have a dedicated query function for the package id registered by libsc. For example, not all wrapper
generators or FFIs (foreign function interfaces) support to read global external variables.
> Add package id getter function

- doc/Doxyfile.in
- doc/example_points.dox
- doc/examples.dox
- example/CMakeLists.txt
- example/points/Makefile.am
- example/points/generate_points.c
- example/points/generate_points2.c
- example/points/generate_points3.c
- example/points/points2.c
- src/p4est_points.h
- src/p8est_points.h
Following up on issue #211
- provide a helper executable to generate example point data
- alos add the brick connectivity (with a slightly different treatment, just for illustrative purpose)
- use MPI-IO to create the point data file (a single file for all MPI processes).
Currently this can only be merged when companion MR https://github.com/cburstedde/libsc/pull/128 which update MPI-IO routines in libsc is merge to. 
The executable that generate point data file need these mpi-io routines in libsc.
> Update points example

- src/p4est_wrap.c
- src/p4est_wrap.h
Currently the function `p4est_wrap_new_p4est` does not reset the data size of the given p4est to 0 and does not free the quadrant data. However, during changing the created p4est_wrap `p.user_int` is used. This PR is a prerequisite for the PR https://github.com/ForestClaw/forestclaw/pull/289.  
We ensure that we do not lose pointers to quadrant data during changing the p4est_wrap by resetting the data size to 0 and freeing the quadrant data in advance in the function `p4est_wrap_new_p4est`.
> Adjust data size handling in wrap_new_p4est

- example/simple/simple2.c
- src/p4est_geometry.c
- src/p4est_geometry.h
- src/p4est_vtk.h
- src/p8est_geometry.h
- src/p8est_vtk.h
Fixed this to be based on develop instead of master.
Proposed changes: Add sphere geometry for use with the 6-tree cubed connectivity. Add configuration to use this geometry in example/simple/simple2.c. Add documentation for p4est_geometry
> sphere2d geometry

- src/p8est_wrap.h
The already merged PR https://github.com/cburstedde/p4est/pull/252 had no adjusted documentation in `p8est_wrap.h`.
Proposed changes: Adding the documentation for the adjustments in the PR https://github.com/cburstedde/p4est/pull/252 also in `p8est_wrap.h`.
> 3D documentation of adjusted wrap data size

- src/p4est_geometry.c
- src/p4est_geometry.h
- src/p4est_to_p8est.h
- src/p8est_connectivity.h
- src/p8est_geometry.c
- src/p8est_geometry.h
The function `p4est_geometry_connectivity_X` is a useful building block for defining custom geometries. I have made it public so that users may take advantage of this.
I also fixed a typo in the geometry file and updated some misleading documentation.
> Geometry API change

- CMakeLists.txt
- cmake/options.cmake
by using a more specific name like "P4EST_BUILD_TESTING" instead of "BUILD_TESTING" this allows parent projects like Forestclaw to select which tests to build and run. This avoids outdated test dependencies causing a top-level project to fail build/test.
Like libsc, since CDash isn't used, there isn't a need for the overhead of `include(CTest)`.
This does _not_ depend on libsc PR just made.
> cmake: P4EST_BUILD_TESTING to allow parent project control

- .github/workflows/ci_cmake.yml
- CMakeLists.txt
- cmake/config.cmake
- config/p4est_soversion.in
- src/Makefile.am
We place the library API version by the libtool convention in one global configuration file.
This is sourced from both the autoconf and cmake build processes.
In passing increase the CI runtime for CMake on MacOS from 20 to 25 minutes.
> Feature soversion

- .github/workflows/ci_cmake.yml
- CMakePresets.json
the runtime of tests on GitHub Actions and CI systems in general
has considerable variance due to different virtual worker hardware
and system loads.
The individual CTest test timeouts increase from 10 => 60 seconds.
The overall job time limit increases to 60 minutes. The only reason
for the overall time limit is so that a hung download or MPI job
doesn't sit "running" for a couple days.
GitHub Actions now has 4-core CI runners, so use all of them by default.
also, include GCC-13 in tests.
also, use the latest Actions for checkout and upload-artifact
Example of nuisance transient timeout failure: https://github.com/cburstedde/p4est/actions/runs/7562394485/job/20592780748)
> CI: improve stability by increasing too-low time limits

- test/CMakeLists.txt
Proposed changes: Since we experienced a failing valgrind CI,
```
Cannot find file: /home/runner/work/p4est/p4est/checkCMakeMPIvalgrind/DartConfiguration.tcl
Memory checker (MemoryCheckCommand) not set, or cannot find the specified program.
Errors while running CTest
```
we include CTest in `test/CMakeLists.txt` to ensure that the valgrind installation is found by ctest.
> CMake: Add CTest inclusion

- src/p4est_io.c
Proposed changes: Analogously to the ForestClaw PR https://github.com/ForestClaw/forestclaw/pull/301, we introduce the function `p4est_file_info_cleanup` to simplify the error management in the function `p4est_file_info`. In addition, there are some fixes of the error management in `p4est_file_info`.
> file_info: Fixes and simplifications

- cmake/GitSubmodule.cmake
- cmake/git.cmake
- example/CMakeLists.txt
For use as subproject, ensure that Git version is generated from the correct project.
Correct the Git Submodule update logic as for submodules ".git" is a file instead of directory. EXISTS handles both cases.
> CMake Git version bugfix

- src/p4est_communication.c
- src/p4est_communication.h
- src/p8est_communication.h
Proposed changes: The function `p4est_bsearch_partition` was placed between `p4est_transfer_custom` and `p4est_transfer_begin`. The function is moved to the top of `p4est_communication.{c,h}` and of `p8est_communication.h` to make the ordering of the functions more consistent.
> Move bsearch function up

- src/p4est_io.c
- test/test_io2.c
Proposed changes: Fix the check for `file` being `NULL` in the function `p4est_file_error_cleanup` to prevent accessing `NULL` in the case of handling a failed call of the open function. In addition, a check abort message is updated.
> Fix file cleanup

- doc/release_notes.txt
Proposed changes: The PR https://github.com/cburstedde/p4est/pull/252 changed the behavior of the function `p{4,8}est_wrap_new_p4est`. This PR adds this information to the release notes of the version 2.8.6.
Edit: @hannesbrandt  pushed his edits of the release notes to this PR to avoid merge conflicts.
> Update release notes

- example/gmt/Makefile.am
- example/gmt/gmt2.c
- example/gmt/gmt_global.h
- example/gmt/gmt_models.c
- example/gmt/gmt_models.h
Introduced a distributed mode to the GMT example, which can be enabled with the `-d` flag. In this mode each process knows only a fraction of the points and at each iteration points are sent to the relevant processes before refinement. Since points are known by multiple processes we avoid duplication by designating a single owner of each point as _responsible_ for propagating it in the next iteration.
Currently the sphere model is the only model set up for distributed mode. However, the communication code is written in such a way that other models could add support without writing their own communication code. 
To support distributed mode a model should (in setup) load a distinct subset of points on each process. Each process must set `model->M` as the number of points loaded on that …
> Feature GMT distributed

- .github/workflows/ci_cmake.yml
Most Apple users now have Apple Silicon ARM64 CPU. Since Apple Silicon introduction, there have been several Apple Silicon-specific issues that needed tweaking. In Jan. 2024, GitHub Actions made Apple Silicon CI free to use so this PR uses that to help detect future issues.
Previously, GitHub Actions used macOS 13 on Intel CPU, which missed numerous issues our developers faced on their Apple Silicon laptops.
> CI: macOS: CMake: use Apple Silicon hardware

- src/p4est.h
- src/p4est_communication.c
- src/p4est_communication.h
- src/p4est_to_p8est.h
- src/p4est_wrap.c
- src/p4est_wrap.h
- src/p8est.h
- src/p8est_communication.h
- src/p8est_wrap.h
- test/test_io2.c
We add a checksum comparison in `wrap_adapt` to check whether coarsening and balancing cancel each other out.
One checksum is computed at the start of the function for the p4est of the input wrap. After refining, coarsening and balancing we compute another checksum, if the total amount of quadrants did not change. If the result p4est has the same checksum as the input p4est, we do not compute a new ghost and mesh for the wrap.
> Checksum comparison in wrap_adapt

- test/test_all6.c
Following up on issue #63.
Proposed changes: reduce the refinement level by 1 to save on memory.
While at it, use the preferred `p4est_have_zlib` runtime check for the z library.
> Feature test all6

- CMakeLists.txt
This PR adds a check if libsc is already a known target in the CMake build system. If
this is the case, registering libsc is skipped.
This is useful for cases when p4est is included as dependency by other software projects, e.g. t8code,
which in turn also depends on libsc. If this check would not be there CMake registers libsc twice which
causes conflicts.
> Check if libsc is already a known target.

- example/CMakeLists.txt
This PR simplifies and unifies examples/CMakeLists.txt file.
In addition, it make examples build by default.
> Cmake examples

- .github/workflows/ci_darwin.yml
GitHub actions CI needs libtool like libsc #181
> ci:macos: Github Actions needs libtool install.

- src/p4est_wrap.c
- src/p4est_wrap.h
- src/p8est_wrap.h
This PR adds a member `old_global_first_quadrant` to the `p4est_wrap_t`.
It stores the global_first_quadrant array of the wrap's p4est before partitioning and can be used to organize data transfers with `transfer_fixed` and `transfer_custom` in between calls to `wrap_partition` and `wrap_adapt`.
> Feature wrap partition

- src/p4est_to_p8est.h
- src/p4est_wrap.c
- src/p4est_wrap.h
- src/p8est_wrap.h
This PR adds two arrays `newly_refined` and `newly_coarsened` to the `p4est_wrap_t`. The arrays store the local quadrant indices of quadrants that were refined or coarsened during the most recent call to `p4est_wrap_adapt`. For refinement, only the index of the quadrant with child id 0 is stored. The arrays are not updated during other function calls like `p4est_wrap_partition`. So, they always index into the local quadrants of the p4est as it was right after adaptation.
The arrays are only initalized and set, if the new wrap parameter `store_adapted` is set to true. Furthermore, we assert that the wrap's p4est is balanced before the adaptation, which ensures a single level of refinement.
> Newly adapted quadrants in wrap

- src/p4est_to_p8est.h
- src/p4est_wrap.c
- src/p4est_wrap.h
- src/p8est_wrap.h
This PR temporarily reinstates the function  `p4est_wrap_set_partitioning` to ensure backwards compatibility.
The function is now marked as outdated.
> Reinstate set_partitioning in wrap

- CMakeLists.txt
- cmake/options.cmake
- doc/author_elsweijer.txt
For our new t8code CMake CI we need the option to build p4est with a system installed SC version.
This option already exists in p4ests autotools build system but does not exist in the CMake build system.
This PR adds this option. The standard behavior of p4ests CMake build system is not altered since the standard policy is to use the SC which ships with p4est.
> CMake option to use a system installed sc

- src/p4est_wrap.c
This PR adds the tree offsets to the indices of recently adapted quadrants, which are stored in the `newly_refined` and `newly_coarsened` arrays introduced in https://github.com/cburstedde/p4est/pull/310, thereby ensuring a unique index for every locally refined quadrant.
> Add tree offsets to newly adapted quadrants in wrap

- doc/doxygen/ghost.dox
- doc/release_notes.txt
- src/p4est.h
- src/p4est_ghost.h
- src/p8est.h
- src/p8est_ghost.h
This PR extends and adds documentation on the ghost layer in p4est. The concrete changes are
- a new Doxygen page on the ghost layer that gives a general introduction (in parts based on https://p4est.org/tutorial-ghost.html),
- add and reference existing examples for ghost,
- fix all Doxygen warnings in `p{4,8}est_ghost.h` and
- extend the documentation on piggies in the `p{4,8}est_quadrant_data` and clarify the role of the piggies.
> Extended documentation of ghost

- doc/doxygen/connectivity.dox
- doc/release_notes.txt
This PR adds a new Doxygen page on the connectivity structure (in parts based on https://p4est.org/tutorial-connectivity.html) in a similar style as the ghost layer page that I added in the previous PR https://github.com/cburstedde/p4est/pull/317.
> Add a doxygen page on the connectivity

- cmake/git.cmake
Currently calling cmake on the source directory generates a file `include/p4est_config.h` with
```
[...]
/* Define to the full name and version of this package. */
#define P4EST_PACKAGE_STRING "p4est 0.0.0"
/* Define to the one symbol short name of this package. */
#define P4EST_PACKAGE_TARNAME "p4est"
/* Define to the home page for this package. */
#define P4EST_PACKAGE_URL ""
/* Define to the version of this package. */
#define P4EST_PACKAGE_VERSION "0.0.0"
/* Version number of package */
#define P4EST_VERSION "0.0.0"
/* Package major version */
#define P4EST_VERSION_MAJOR 0
/* Package minor version */
#define P4EST_VERSION_MINOR 0
/* Package point version */
#define P4EST_VERSION_POINT 0
```
as reported in https://github.com/DLR-AMR/t8code/issues/1294.
The reason for the described …
> Fix git-version-gen path

- example/spheres/spheres2.c
This PR changes some of the default  parameters in `example/spheres/spheres2.c` in order to create results that better fit the expectations for this example. In particular, we
- set `maxlevel` above `minlevel`, so that the forest is adaptively refined,
- increase `spherelems` to obtain higher resolution of the spheres and
- increase `lfraction` to obtain multiple spheres.
Some of the spheres in this example overlap each other or lie partially outside of the forest, thereby demonstrating that the code is able to deal with these special cases as well.
> Change default parameters in spheres2.c

- cmake/install.cmake
This PR addresses among others the issue of tarball naming in the CMake build system. Previously, an uninitialized variable, `git_version`, was used for the version in the package name, leading to incorrect tarball names.
Moreover,  this PR introduces a new CMake target `GenerateVersionFile` to generate the file `.tarball-version` analogous to the file used in the Autotools-based creation of a tarball in p4est.
Then the file `.tarball-version` is used by the script `git-version-gen` to get the version in the case `.git` is not present, as it is the case for creating a tarball. This ensures a correctly populated `p4est_config.h` after configuring in a tarball directory.
Currently, the CMake target `GenerateVersionFile` is only build if some arbitrary build command is executed. In …
> Fix tarball versioning

- doc/doxygen/forest.dox
- doc/release_notes.txt
This PR adds a new Doxygen page on the forest structure (in parts based on https://p4est.org/tutorial-forest.html) in a similar style as the ghost layer page that I added in the previous PR https://github.com/cburstedde/p4est/pull/317.
Additionally, this PR updates the release notes for the changes in https://github.com/cburstedde/p4est/pull/326 since they were missing in the release notes.
> Add a doxygen page on the forest workflow

- CMakeLists.txt
- doc/author_knapp.txt
Following up on issue https://github.com/cburstedde/libsc/issues/206
Proposed changes: Use a seperate command instead of a generator expression. It prevents linker-errors with p4est if these expression fails to be properly generated.
> seperat link command for Winsock

- src/p4est_bits.c
- src/p4est_bits.h
- src/p4est_io.c
- src/p4est_points.c
- src/p4est_search.c
- src/p4est_to_p8est.h
- src/p8est_bits.c
- src/p8est_bits.h
- test/test_quadrants2.c
Create functions to export any corner coordinates and face or odge midpoint of any valid p4est quadrant. The quadrant must thus be inside the unit tree. The coordinates may or may not be on any boundary of the unit tree.
This is an extension on top of #334. It can help the user create indexing the mesh topology and/or to use hashing to determine the quadrant connectivity.
> Calculate quadrant boundary coordinates

- src/p4est_bits.c
- src/p4est_bits.h
- src/p4est_io.c
- src/p4est_points.c
- src/p4est_search.c
- src/p4est_to_p8est.h
- src/p8est_bits.c
- src/p8est_bits.h
- test/test_quadrants2.c
Previously, coordinates were treated like from the lower left corner of a quadrant.  Thus, they were not allowed to touch any high face of the unit tree.  We change this to make coordinates valid on all tree boundaries.  We also allow coordinates as deep as P4EST_MAXLEVEL (quadrant midpoints).
The idea is to use the coordinates to index any boundary object of a quadrant, thus any of its corners and face, edge, and volume midpoints.
This may affect use of the coordinates outside of p4est. Any comments @tisaac?
> Feature boundary coordinates

- .github/workflows/ci.yml
- .github/workflows/ci_cmake.yml
- .github/workflows/ci_darwin.yml
- .github/workflows/composite-unix/action.yml
- CMakeLists.txt
- cmake/options.cmake
- cmake/p4est_config.h.in
- configure.ac
- doc/release_notes.txt
- test/CMakeLists.txt
- test/test_io2.c
- test/test_loadsave2.c
This PR provides analogous changes as implemented in libsc in the PR https://github.com/cburstedde/libsc/pull/214. This means that this PR adds an option in Autoconf and in CMake to disable the file I/O checks, which cause frequent CI failures due to a busy file system on the CI runners. This option is used in the three CI workflows.
In addition, this PR adds `test_loadsave3` as target in CMake since it was missing and this PR fixes a typo in `CMakeLists.txt` that caused the CMake build to fail on Windows.
> Avoid CI fails due to busy file system

- .github/workflows/ci_valgrind.yml
The PR https://github.com/cburstedde/p4est/pull/337 was missing the changes for the valgrind CI workflow. This PR adds them.
> Deactivate file checks for valgrind CI

- example/simple/simple2.c
- example/simple/simple3.c
- src/p4est_geometry.c
- src/p4est_geometry.h
- src/p4est_to_p8est.h
- src/p8est_geometry.h
So far, calling a geometry map was left to the user and required reading quite some documentation.
Here we introduce the function p4est_geometry_transform_coordinates that does the job.
It can be called given any valid geometry structure to map quadrant reference coordinates into space.
Along the way, we add minor documentation fixes.
Any comments @pkestene ?
> Add generic geometry transformation

- example/CMakeLists.txt
- example/mesh/Makefile.am
- example/particles/Makefile.am
- example/points/Makefile.am
- example/timings/Makefile.am
This PR changes the naming scheme of the executables in example/CMakeLists.txt to match the `p4est_` naming scheme used in Autotools.
Additionally, it adds the userdata example to example/CMakeLists.txt.
Furthermore, it adds some missing files from the example folders to the autotools distribution.
> Unify example executable names

- README
- doc/author_doehring.txt
Following up on issue # . -
I would add the `make`, `make install` commands for completeness (and especially for people less familiar with the GNU build process, e.g. for folks coming from Julia.)
> Update README: Install instructions

- .github/workflows/ci_cmake.yml
UCRT is the recommend environment prefix of the MSYS2 project and what Microsoft promotes as well. UCRT is what MSYS2 end-users would be using. This makes the CI tests best represent what end users experience.
> CI:Windows:MSYS2: use UCRT packages
